function Exergia_Com_graf(X1, YMatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 08-Jan-2018 18:28:49

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.12598393574297 0.415699481865286 0.462369477911645 0.542849740932642]);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',1,'Parent',axes1);
set(plot1(1),'MarkerSize',8,'Marker','square','Color',[0 0 1]);
set(plot1(2),'MarkerSize',8,'Marker','square','Color',[1 0 0]);
set(plot1(3),'Visible','off','Marker','o','Color',[0 0 1]);
set(plot1(4),'Marker','o','Color',[1 0 0]);
set(plot1(5),'Marker','*','Color',[0 0 1]);
set(plot1(6),'Marker','*','Color',[1 0 0]);
set(plot1(7),'Visible','off','MarkerSize',8,'Marker','x','Color',[0 0 1]);
set(plot1(8),'MarkerSize',8,'Marker','x','Color',[1 0 0]);
set(plot1(9),'Marker','diamond','Color',[0 0 1]);
set(plot1(10),'Marker','diamond','Color',[1 0 0]);
set(plot1(11),'LineWidth',2,'Color',[0 0.800000011920929 1]);
set(plot1(12),'LineWidth',2,'Color',[1 0.600000023841858 0.600000023841858]);

% Create xlabel
xlabel('Cell Temperature [ºC]','FontName','Times New Roman');

% Create ylabel
ylabel('Exergetic Efficiency [%]','FontName','Times New Roman');

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[30 200]);
%ylim(axes1,[9 26]);
ylim(axes1,[5 25]);
%ylim(axes1,[10 31]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Times New Roman','FontSize',11,'XGrid','on','YGrid',...
    'on');
% Create textbox
annotation(figure1,'textbox',...
    [0.132206617352639 0.487866496439135 0.164873275799379 0.0785714269393967],...
    'String','\eta_{ref} = 10%',...
    'FontName','Times New Roman',...
    'FitBoxToText','off',...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.443923257729456 0.827599832522121 0.157515777395298 0.0777202072538864],...
    'String','\eta_{ref} = 20%',...
    'FontName','Times New Roman',...
    'FitBoxToText','off',...
    'EdgeColor','none');

