function gera_graf_com_frio(X1, YMatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 06-Jan-2018 10:51:30

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.12598393574297 0.415699481865286 0.462369477911645 0.542849740932642]);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',1,'Parent',axes1);
set(plot1(1),'MarkerSize',8,'Marker','square','Color',[0 0 1]);
set(plot1(2),'MarkerSize',8,'Marker','square','Color',[1 0 0]);
set(plot1(3),'Marker','o','Color',[0 0 1]);
set(plot1(4),'Marker','o','Color',[1 0 0]);
set(plot1(5),'Visible','off');
set(plot1(6),'Visible','off');

% Create xlabel
xlabel('Solar Irradiance [W/m^2]','FontName','Times New Roman');

% Create ylabel
ylabel('Maximum Temperature [ºC]','FontName','Times New Roman');
ylim(axes1,[50 200]);

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Times New Roman','FontSize',11,'XGrid','on','YGrid',...
    'on');
% Create textbox
annotation(figure1,'textbox',...
    [0.41410642570281 0.529620034542317 0.157515777395297 0.0777202072538863],...
    'String','\eta_{ref} = 20%',...
    'FontName','Times New Roman',...
    'FitBoxToText','off',...
    'EdgeColor','none',...
    'BackgroundColor',[1 1 1]);

% Create textbox
annotation(figure1,'textbox',...
    [0.388446643717724 0.764939552581954 0.146428567596844 0.0785714269393967],...
    'String','\eta_{ref} = 10%',...
    'FontName','Times New Roman',...
    'EdgeColor','none',...
    'BackgroundColor',[1 1 1]);

