function gera_graf_com_calor(X1, YMatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 06-Jan-2018 10:56:48

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.12598393574297 0.415699481865286 0.462369477911645 0.542849740932642]);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',1,'Parent',axes1);
set(plot1(1),'Visible','off');
set(plot1(2),'Visible','off');
set(plot1(3),'MarkerSize',8,'Marker','x','Color',[0 0 1]);
set(plot1(4),'MarkerSize',8,'Marker','x','Color',[1 0 0]);
set(plot1(5),'Marker','diamond','Color',[0 0 1]);
set(plot1(6),'Marker','diamond','Color',[1 0 0]);

% Create xlabel
xlabel('Solar Irradiance [W/m^2]','FontName','Times New Roman');

% Create ylabel
ylabel('Maximum Temperature [ºC]','FontName','Times New Roman');
ylim(axes1,[0 400]);

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Times New Roman','FontSize',11,'XGrid','on','YGrid',...
    'on');
% Create textbox
annotation(figure1,'textbox',...
    [0.308089500860582 0.849124105600795 0.164658634538153 0.0777202072538862],...
    'String','\eta_{ref} = 10%',...
    'FontName','Times New Roman',...
    'FitBoxToText','off',...
    'EdgeColor','none',...
    'BackgroundColor',[1 1 1]);

% Create arrow
annotation(figure1,'arrow',[0.369642857142857 0.410714285714285],...
    [0.861904761904762 0.795238095238097],'HeadWidth',6,'HeadLength',6);

% Create textbox
annotation(figure1,'textbox',...
    [0.423034997131381 0.457340243428235 0.146428567596844 0.0785714269393967],...
    'String','\eta_{ref} = 20%',...
    'FontName','Times New Roman',...
    'EdgeColor','none',...
    'BackgroundColor',[1 1 1]);

% Create arrow
annotation(figure1,'arrow',[0.491967871485943 0.483935742971887],...
    [0.527165062916359 0.57638786084382],'HeadWidth',6,'HeadLength',6);




