function Tmax_Sem_calor_graf(X1, YMatrix1)
%CREATEFIGURE1(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 09-Jan-2018 18:04:16

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.12598393574297 0.415699481865286 0.462369477911645 0.542849740932642]);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',1,'Parent',axes1);
set(plot1(1),'Marker','square','Color',[0 0.498039215803146 0]);
set(plot1(2),'Visible','off','Marker','square','Color',[0 0 1]);
set(plot1(3),'Visible','off','Marker','square',...
    'Color',[0 0.498039215803146 0]);
set(plot1(4),'Visible','off','Marker','o','Color',[0 0.498039215803146 0]);
set(plot1(5),'Marker','o','Color',[0 0 1]);
set(plot1(6),'Marker','o','Color',[1 0 0]);
set(plot1(7),'Marker','*','Color',[0 0.498039215803146 0]);
set(plot1(8),'Marker','*','Color',[0 0 1]);
set(plot1(9),'Marker','*','Color',[1 0 0]);
set(plot1(10),'Visible','off','Marker','x','Color',[0 0.498039215803146 0]);
set(plot1(11),'Marker','x','Color',[0 0 1]);
set(plot1(12),'Marker','x','Color',[1 0 0]);
set(plot1(13),'Visible','off','Marker','diamond',...
    'Color',[0 0.498039215803146 0]);
set(plot1(14),'Marker','diamond','Color',[0 0 1]);
set(plot1(15),'Marker','diamond','Color',[1 0 0]);

% Create xlabel
xlabel('Solar Irradiance [W/m^2]','FontName','Times New Roman');

% Create ylabel
ylabel('Maximum Temperature [ºC]','FontName','Times New Roman');

% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[40 120]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Times New Roman','FontSize',11,'XGrid','on','YGrid',...
    'on');
% Create textbox
annotation(figure1,'textbox',...
    [0.446434011909706 0.828715365239295 0.0751177122282247 0.0565298710865889],...
    'String','10%',...
    'FontName','Times New Roman',...
    'FitBoxToText','off',...
    'EdgeColor','none',...
    'BackgroundColor',[1 1 1]);

% Create textbox
annotation(figure1,'textbox',...
    [0.377547628939398 0.566750629722922 0.161245474508878 0.0593020314585008],...
    'String','\eta_{ref} = 20%',...
    'FontName','Times New Roman',...
    'FitBoxToText','off',...
    'EdgeColor','none',...
    'BackgroundColor',[1 1 1]);

% Create textarrow
annotation(figure1,'textarrow',[0.325431034482759 0.359913793103448],...
    [0.82267758186398 0.785894206549118],'TextBackgroundColor',[1 1 1],...
    'String',{'\eta_{ref} = 5%'},...
    'HeadWidth',6,...
    'HeadLength',6,...
    'FontName','Times New Roman');

